### ISSUE TITLE
weird dependency checksum mismatch

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry-incubator/cf-operator#37]
I ran command under go1.11.2:
```
$ GO111MODULE=on go mod vendor
go: downloading k8s.io/apimachinery v0.0.0-20180621070125-103fd098999d
go: downloading github.com/pkg/errors v0.8.0
go: downloading github.com/cppforlife/go-patch v0.0.0-20171006213518-250da0e0e68c
go: downloading k8s.io/client-go v0.0.0-20180806134042-1f13a808da65
go: downloading github.com/spf13/viper v1.2.1
go: downloading github.com/spf13/cobra v0.0.3
go: downloading sigs.k8s.io/controller-runtime v0.1.4
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/spf13/afero v1.1.2
go: verifying k8s.io/client-go@v0.0.0-20180806134042-1f13a808da65: checksum mismatch
        downloaded: h1:kQX7jEIMYrWV9XqFN4usRaBLzCu7fd/qsCXxbgf3+9g=
        go.sum:     h1:wQUEIVcXYxsDE8RXfUufo1nfnkeH/BEPhT175YIzea4=
```

**Comment by viovanov** [comment]
@edwardstudy did you try more than once? is it persistent?

**Comment by edwardstudy** [comment]
Yes. I had raised a PR about it:
https://github.com/cloudfoundry-incubator/cf-operator/pull/38

Did you meet this mismatch sha1sum?

Vlad Iovanov <notifications@github.com> 于2018年12月11日周二 下午3:57写道：

**Comment by edwardstudy** [comment]
Yes. I had raised a PR about it: https://github.com/cloudfoundry-incubator/cf-operator/pull/38

Did you meet this mismatch sha1sum?

**Comment by manno** [comment]
I think we can work around this: https://github.com/cloudfoundry-incubator/cf-operator/pull/38#issuecomment-446149256

**Comment by edwardstudy** [comment]
Yes. It works and only just works.

**Comment by aduffeck** [comment]
JFYI we switched the checksum in git to what go 1.11.2 and 1.11.0 produce in https://github.com/cloudfoundry-incubator/cf-operator/pull/49 and it's working fine for all of us and for the CI. Nobody's using 1.11.1 here anymore.
