### ISSUE TITLE
failed calling webhook "mutate-pods.fissile.cloudfoundry.org"

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/cf-operator#436]
After the cf-operator pod crashes it can not be started again because of:
```
FailedCreate   ReplicaSet   Error creating: Internal error occurred: failed calling webhook "mutate-pods.fissile.cloudfoundry.org": Post https://10.245.0.87:2999/mutate-pods?timeout=30s: dial tcp 10.245.0.87:2999: connect: connection refused
```

To me this looks like a circular dependency, as in to schedule the cf-operator pod, k8s needs to call the cf-operator webhook, which is not available since the pod is not running.

**Comment by manno** [comment]
Deleting the webhook configurations will work around this issue:

Check for them and delete the cf-operator ones, or just run this to delete all:

```
kubectl delete validatingwebhookconfigurations --all
kubectl delete mutatingwebhookconfigurations --all
```

**Comment by rkoster** [comment]
I found, I'm able to fix this issue by not deploying the cf-operator in the same namespace, the one it is operating on. But this is not supported by the helm chart. Would this be the preferred deployment model or is there an option to make the `validatingwebhookconfigurations` and `mutatingwebhookconfigurations` skip the cf-operator pod?

**Comment by qu1queee** [comment]
@rkoster as @manno mentioned about, you need to clean up your webhooks configuration if you want to re-install on the same namespace. Reason behind, is that every new deployment of the cf-operator, will generate a new service with a new `ClusterIP`, so you want your webhooks to point to the right one. 

As with any helm installation, you required to do some pre-processing. Cleaning the webhooks is one of them. 
The only way to automate this for you, is to use something similar to what I have in this [file](https://github.com/cloudfoundry-incubator/cf-operator/blob/master/dev-env-havener.yaml), it basically use a tool call `havener`, that runs some `pre-processing` steps, prior to the `helm install`.

**Comment by manno** [comment]
@rkoster if you can't run `helm install --namespace MYCUSTOMNAMESPACE https://s3.amazonaws.com/cf-operators/release/helm-charts/cf-operator-v0.3.1%2B5.gb97ec705.tgz`, I think that would be a bug.

**Comment by drnic** [comment]
For myself and others, to restart `cf-operator`:

```
restart() {
  kubectl delete validatingwebhookconfigurations --all
  kubectl delete mutatingwebhookconfigurations --all
  kubectl delete pod -l name=cf-operator -n scf
}
```

**Comment by drnic** [comment]
Is there a better way to select just the `cf-operator` webhooks in the example above?
