### ISSUE TITLE
Be consistent about docker org environment variable

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/cf-operator#438]
Currently [`OPERATOR_DOCKER_ORGANIZATION`] is used when building images, but [`DOCKER_IMAGE_ORG`] is used when cf-operator actually runs; this means if only the former is set, `make/up` will fail to find the right image.  This is kind of annoying.

[`OPERATOR_DOCKER_ORGANIZATION`]: https://github.com/cloudfoundry-incubator/cf-operator/blob/83f20bdf922714223abcb8eb4f5d62e9e5b08b99/bin/build-image#L14
[`DOCKER_IMAGE_ORG`]: https://github.com/cloudfoundry-incubator/cf-operator/blob/cd550ecca07e859ea54ba564d377ab1af0c0bce1/cmd/internal/root.go#L124

**Comment by manno** [comment]
Seems to affect just one script.
