### ISSUE TITLE
What is status of v0.4.1?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cf-operator#587]
v0.4.1 has been tagged but not released. What happens next in the steps towards a release?

**Comment by viovanov** [comment]
Hey @drnic - we're waiting for a resolution for this bug:
https://www.pivotaltracker.com/story/show/168510894

Same bug you discovered during the lab at Summit.
Once we have this in, we'll release.

**Comment by drnic** [comment]
Are tags created and moved over time until a release is created? Or what is
this project’s relationship between a tag without a release, and a
release/tag? Hopefully the question makes sense; normally a project cuts a
tag as part of a release. We’re not doing that here, so am asking that
triggers a tag to be pushed, but with known issues/features yet to be
included.
-- 
Dr Nic Williams
Stark & Wayne LLC
http://starkandwayne.com
+61 437 276 076
twitter @drnic

**Comment by bkrannich** [comment]
👍 for @drnic's comment. I also was wondering about the same recently and I'd agree to advocating for the "regular" approach to tagging as described by Dr. Nic.

**Comment by drnic** [comment]
Closing with public release of 0.4.2
