### ISSUE TITLE
Allow listing of s3 bucket cf-operator objects

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cf-operator#593]
The `cf-operator` s3 bucket is mentioned in:

- https://github.com/cloudfoundry-incubator/cf-operator/blob/master/deploy/helm/cf-operator/README.md#installing-the-latest-stable-chart
- https://github.com/cloudfoundry-incubator/cf-operator/releases/tag/v0.4.0 under "Assets"

But I cannot list its assets as expected:

```bash
$ aws s3 ls s3://cf-operators/
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

Could we change the bucket to allow public listing please?

**Comment by qu1queee** [comment]
There is a [listing](https://cf-operators.s3.amazonaws.com/helm-charts/index.html) for releases, you can use it in the future, I hope it helps.
