### ISSUE TITLE
When I run `bin/build-helm` I want it to include a valid upstream docker tag regardless if I have a dirty dir

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cf-operator#610]
I'm trying to test changes to the helm chart, but when I run `bin/build-helm` my `values.yaml` includes `tag: v0.4.1-dirty-76.g3735895c` which is not a valid upstream docker hub tag.

If I haven't made any changes to the contents of the docker image (cf-operator itself) then I would want to use a valid docker tag, which would be `tag: v0.4.1-76.g3735895c` in this case.

**Comment by viovanov** [comment]
@drnic have you tried setting the following in an `.envrc.local`?

```
export DOCKER_IMAGE_TAG=vladi-dev
```

This is what I used for development.

**Comment by drnic** [comment]
Ok thanks for that.
