### ISSUE TITLE
Why might I get a timeout creating a BOSHDeployment?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cf-operator#620]
```
$ kaf docs/examples/bosh-deployment/boshdeployment-with-custom-variable.yaml -n scf
secret/nats-deployment.var-custom-password configured
configmap/nats-manifest unchanged
configmap/ops-scale unchanged
Error from server (Timeout): error when creating "vendor/cf-operator/docs/examples/bosh-deployment/boshdeployment-with-custom-variable.yaml": Timeout: request did not complete within requested timeout 30s
```

During this time, there are no logs in cf-operator related to the attempted `BOSHDeployment` creation.

Ideas why this might happen?

**Comment by drnic** [comment]
I've upgraded to latest cf-operator and this issue no longer appears. I'll leave ticket open briefly in case anyone can share some reasons why this might have happened.

**Comment by bkrannich** [comment]
Getting the same thing here, even with what I believe is the latest version of the operator: v0.4.1-60.g642832d0 taken from https://github.com/starkandwayne/bootstrap-kubernetes-demos/blob/ba8960a26b63d6fa5315cbd5b23462cf34352281/bin/bootstrap-system-cf-operator#L6

The thing is: Even a complete purge of all namespaces (the operator one included) doesn't seem to help.

**Comment by viovanov** [comment]
@bkrannich can you please try the latest version (0.4.2), and also maybe increase the `contextTimeout` setting, as described here: https://github.com/cloudfoundry-incubator/cf-operator/blob/master/deploy/helm/cf-operator/README.md#configuration

**Comment by bkrannich** [comment]
@viovanov Sorry, missed to reply here. Turns out, I unintentionally dropped `--set "operator.watchNamespace=scf"` from my helm install, so the operator wasn't listening to the namespace into which I uploaded SCF.

Unless @drnic has additional topics, I believe we can close this one.
