### ISSUE TITLE
Helm chart version to match operator version?

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry-incubator/cf-operator#623]
Looking at https://github.com/cloudfoundry-incubator/cf-operator/blob/604925f0deef026b92ad4fd185d58f5b352cea86/deploy/helm/cf-operator/Chart.yaml#L4, it seems like the Helm chart version is hardcoded there. Would it make sense to have the Helm chart version match the version of the actual operator TGZ file for consistency and "upgradeability"?

**Comment by manno** [comment]
That directory is not deployable, but used by `bin/build-helm` to build the actual helm chart in.

The actual version is always calculated from git.

**Comment by bkrannich** [comment]
@manno: I looked into https://s3.amazonaws.com/cf-operators/helm-charts/cf-operator-v0.4.1%2B92.g77e53fda.tgz as referenced in your https://github.com/SUSE/scf/blob/7178d32d95fa83efa60cffba99346abb4f14dbd1/INSTALL.md#install-cf-operator and Chart.yaml has `version: 0.0.1`. Is this something that should read `version: 0.4.1` instead?

**Comment by manno** [comment]
I misunderstood :) 
Thought this was about https://github.com/cloudfoundry-incubator/cf-operator/blob/master/deploy/helm/cf-operator/values.yaml#L5 

I guess the 0.0.1 is the version of the helm chart. We will have to version it properly when we do https://www.pivotaltracker.com/story/show/165014706
