### ISSUE TITLE
Q: Why does operator.watchNamespace need to exist for cf-operator to deploy successfully?

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry-incubator/cf-operator#624]
Deploying cf-operator using a separate target namespace as described in https://github.com/SUSE/scf/blob/7178d32d95fa83efa60cffba99346abb4f14dbd1/INSTALL.md#install-cf-operator with namespace `scf`, I found that the operator deployment fails with

```
cf-operator command failed. Failed to create new manager.: failed to setup hooks: setting the operator namespace label: getting the namespace object: namespaces "scf" not found
```

Is this intentional or would it be ok to let the operator deployment pass successfully and do the rest of the initialization once the namespace exists?

**Comment by manno** [comment]
The namespace needs to exist, before running `helm`.

**Comment by bkrannich** [comment]
@manno: Wow, that was quick! I guess the PR would also work in cases the namespace was created before (e.g. in `helm upgrade` cases)?

**Comment by bkrannich** [comment]
> I guess the PR would also work in cases the namespace was created before (e.g. in helm upgrade cases)?

Seems like it doesn't... I am now getting
```
Error: release cf-operator failed: namespaces "scf" already exists
```
if the namespace exists. Not sure what would happen during an update scenario of the operator.
