### ISSUE TITLE
Image Pull Policy should be consistent

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry-incubator/cf-operator#634]
Currently, the ImagePullPolicy can be configured in the helm chart for the cf-operator deployment. This property is not propagated to subsequent jobs like dm,bpm or ig. If the kubernetes cluster consists of more than 2 nodes, this can lead to inconsistent images used for different jobs.

To ensure that the same images are used for subsequent jobs, the cf-operator should always use a SHA as reference to the docker image. 
Even if the ImagePullPolicy is set to Always it could happen that different images are used for subsequent jobs on different k8s nodes.

**Comment by kramerul** [comment]
It seems to be very difficult to get the SHA inside a running container image.

**Comment by manno** [comment]
The way we calculate the version from Git should make sure, that a single version always corresponds to a specific git commit.
Since docker images are referenced by that version, I fail to understand how this can lead to inconsistent images. 
Kubernetes should just pull the image with the correct version, if it's missing?

**Comment by kramerul** [comment]
> The way we calculate the version from Git should make sure, that a single version always corresponds to a specific git commit.
> Since docker images are referenced by that version, I fail to understand how this can lead to inconsistent images.
> Kubernetes should just pull the image with the correct version, if it's missing?

This only causes problems in development environments. We had trouble with several strange behaviours of the operator. It took us days to find out, that they were caused by different versions of the image running on the different nodes within our cluster.

For productive environments this is not really required.
