### ISSUE TITLE
If bpm job crashes there is no hint in cf-operator for this fact

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry-incubator/cf-operator#646]
cf-operator should log something if bpm jobs fails. It's also (for us) not possible to get the logs of the failed bpm job. Is there a way to see these logs?

**Comment by edwardstudy** [comment]
@kramerul Hi. Could you please explain what it means that `not possible to get the logs of the failed bpm job`?

**Comment by kramerul** [comment]
If the bpm job finishes (with an error) it's not possible to call 

```bash
kubectl log <finished jo>
```

because the pod doesn't exist any mode.

**Comment by edwardstudy** [comment]
@kramerul Could you list failed kube job:

**Comment by kramerul** [comment]
I don't remember the exact environment. I think it was somehow related to ##645

**Comment by edwardstudy** [comment]
@kramerul Could you please use master branch to reproduce this? #645 was also fixed.

**Comment by manno** [comment]
'stern' does a great job at collecting and printing container logs:

`stern --all-namespaces '.*dm.*' --container-state terminated`

**Comment by edwardstudy** [comment]
@kramerul Could you please use the latest cf-operator to retry? 

Reopen it if it occurred again.
