### ISSUE TITLE
Q: Operator version naming

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry-incubator/cf-operator#689]
I am wondering why the operator version used at https://cf-operators.s3.amazonaws.com/helm-charts/index.html contains a `+` sign between minor and patch version whereas the contained Chart.yaml mentions the same `version`, but with a `-` sign instead.

**Comment by viovanov** [comment]
@bkrannich `+` is the correct sign for semver to denote build metadata.
We replace it with a `-` because docker tags don't allow `-`.

We should be consistent and have the filename also use a `-`.

**Comment by bkrannich** [comment]
Also, because you can then avoid URL encoding `+` with `%2B`.

**Comment by viovanov** [comment]
#691 should fix this

**Comment by bkrannich** [comment]
Yeah, looking at https://cf-operators.s3.amazonaws.com/helm-charts/index.html the `+`s changed to `-`s a couple of releases ago. Thanks for the prompt follow-up!
