### ISSUE TITLE
Pod mutator didn't work after recreating watching namespace

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry-incubator/cf-operator#690]
Pod mutator didn't work after recreating watching namespace, because we only did labelling this on setup: https://github.com/cloudfoundry-incubator/cf-operator/blob/882523badf27b326445fd467657aab797a869b57/pkg/kube/controllers/controllers.go#L88-L92

And a namespace hadn't this label, so pod mutator didn't work and caused Kube Service selector didn't work because we lost pod ordinal labels.

**Comment by viovanov** [comment]
@edwardstudy sounds like we require a restart of the operator if the namespace goes away?
Re-creating the namespace with the correct label would also fix this. We could document.

What would you expect to happen?

**Comment by edwardstudy** [comment]
@viovanov Maybe cf-operator can want the watched namespace and relabel it.

**Comment by edwardstudy** [comment]
@viovanov Maybe cf-operator can want the watched namespace and relabel it.

**Comment by qu1queee** [comment]
Potential fix in https://github.com/SUSE/kubecf/pull/169

**Comment by qu1queee** [comment]
Above PR was merged, this issue can be closed now
