### ISSUE TITLE
Failure adding environment variable to instance group job

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/cf-operator#729]
When adding an environment variable using an ops-file, if the env key doesn't exist on the original BPM config, the cf-operator won't add it to the final pod container.

## Expected behaviour

cf-operator should add the environment variable whether we are replacing an existing BPM environment variable, or adding a new one.

## Context

We should not need to add a patch like this  https://github.com/SUSE/kubecf/blob/cce59cd41649853ab5e05aee7318b41f53271eaf/bosh/releases/pre_render_scripts/api/routing-api/bpm/patch_bpm.sh#L16 to BPM. https://github.com/SUSE/kubecf/blob/cce59cd41649853ab5e05aee7318b41f53271eaf/deploy/helm/kubecf/assets/operations/instance_groups/api.yaml#L159 should be enough.

It will also enable https://github.com/SUSE/kubecf/blob/master/deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml#L79-L81.

**Comment by edwardstudy** [comment]
Same as https://github.com/cloudfoundry-incubator/cf-operator/issues/734 if you want to update `envs, ports or something from `properties.quarks`.
