### ISSUE TITLE
Need a means to capture logs during upgrades

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/cf-operator#840]
As seen with kubecf, upgrades that rely on operator are difficult to troubleshoot as logs within the pods aren't accessible and then lost forever as part of the current workflow.

We need to design a way of having a way of capturing the activity in these pods somewhere. Perhaps we have a support container that runs adjacent during an upgrade which has a log siphon that persists.

**Comment by viovanov** [comment]
@gaktive this is not a concern that should lie with the operator.
There are logging stacks that can be used on Kubernetes. Even if the operator wasn't around, you'd still have the same problem with job containers that go away.

I've created https://github.com/cloudfoundry-incubator/kubecf/issues/537 on kubecf to help out with this.
