### ISSUE TITLE
Install on AKS fails with "Failed to watch *v1.Pod: unknown (get pods)" from "quarks-job"

### ISSUE THREAD

**Issue by jakobyte1024** [cloudfoundry-incubator/cf-operator#878]
Hello cf-operator experts,

I am trying to deploy KubeCF on AKS and came to a problem.
Unfortunately I do not have a idea what the problem is.
Please tell me if I can pass helpful information here.
Thank you in advance.

Sincerly, jakobyte1024

**Describe the bug**
Installation of cf operator & kube-cf bundle on AKS fails. I used kubecf bundle 1.01, which uses cf-operator 3.3.0+0.gf32b521e helm chart.
I tested with AKS 1.15.10 and 1.16.7.
CF Operator installs well.
KubeCF pulls and initializes for a couple of minutes. But it stucks in a loop with following logs (bigger log file attached)
`cf-operator cf-operator-quarks-job-5bb6fc7bd6-5qj27 quarks-job E0401 08:21:36.260296       1 reflector.go:280] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to watch *v1.Pod: unknown (get pods)
cf-operator cf-operator-69848766f6-h52b9 cf-operator 2020-04-01T08:21:36.580Z	INFO	active-passive-reconciler	quarksstatefulset/active_passive_reconciler.go:210	Succesfully exec cmd in container: database, inside pod: kubecf-database-0
cf-operator cf-operator-quarks-job-5bb6fc7bd6-5qj27 quarks-job E0401 08:21:37.321528       1 reflector.go:280] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to watch *v1.Pod: unknown (get pods)`

[cf-operator kube-system dashboard-metric.txt](https://github.com/cloudfoundry-incubator/cf-operator/files/4419469/cf-operator.kube-system.dashboard-metric.txt)

**To Reproduce**
Use AKS 1.15.10
`helm install cf-operator --namespace cf-operator cf-operator.tgz --set "global.operator.watchNamespace=kubecf"`
`helm install kubecf --namespace kubecf kubecf.tgz --values values.yaml`

**Expected behavior**
KubeCF pulls and starts, is reachable afterwards.

**Environment**
 - CF-Operator 3.3.0+0.gf32b521e
 - AKS 1.15.10 and 1.16.7.
 - KubeCF v1.0.1

**Comment by viovanov** [comment]
Hi @jakobyte1024 - got hands on an AKS cluster - latest kubecf master and cf-operator are deploying and running well on `1.15.10`. 
I'll try the `1.0.1` release next.

**Comment by viovanov** [comment]
@jakobyte1024 1.0.1 works as well.

my commands

```
k create namespace cf-operator
helm install --namespace cf-operator cf-operator ./cf-operator.tgz --set "global.operator.watchNamespace=kubecf"
helm install --namespace kubecf --values values.yaml kubecf ./kubecf.tgz
```

values yaml is the default, with a custom domain name..

I need more help reproing :)

**Comment by viovanov** [comment]
@jakobyte1024 I was able to repro with a different cluster - looks like a permission issue, I'll report back when I find something

**Comment by viovanov** [comment]
@jakobyte1024 please test with this release: https://github.com/cloudfoundry-incubator/cf-operator/releases/tag/v4.3.1, and reopen if the issue persists. Thanks!

**Comment by jakobyte1024** [comment]
Hello @viovanov ,
thank you very much for helping here ! I am looking forward to test :) 
I am currently on vacation, so I'll test the new version next week earliest.
If you need my feedback / test ASAP, please let me know !
