### ISSUE TITLE
Split credsgen in a separate golang module

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/cf-operator#892]
**Is your feature request related to a problem? Please describe.**
EiriniX depends on parts of cf-operator code, the critical point is the `credsgen` package https://github.com/cloudfoundry-incubator/cf-operator/tree/master/pkg/credsgen see https://github.com/SUSE/eirinix/issues/23

**Describe the solution you'd like**
I'd like to split the credsgen module in a separate package from cf-operator. By looking at the deps of credsgen I couldn't see a valid reason to not do so. The credsgen package doesn't need the operator code as far as I can tell as it is independent (please correct me if I'm wrong) and it can be decoupled easily to be managed separately outside of kubernetes/client-go and controller-runtime bumps.

**Describe alternatives you've considered**
Duplicate cf-operator code on EiriniX

**Comment by viovanov** [comment]
@mudler since you've got a solution, and we're not planning to make the operator more consumable as a library (at least right now), I'm going to close this
