### ISSUE TITLE
Add copy/move functionality to ops-file support

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/cf-operator#900]
**Is your feature request related to a problem? Please describe.**

We sometimes want to move jobs inside the deployment manifest to a different instance group. Most recent example is moving the log-cash job away from doppler.

This functionality has previously been requested by the [release engineering team](https://github.com/cppforlife/go-patch/issues/5#issuecomment-375124023) as well:

>Better support for changing colocation strategies would be super useful. We're trying to start working on a small-footprint deployment manifest for CF, but we're not sure how we'll keep properties in sync between our main manifest and our small-footprint manifest

The change has essentially been rejected by the bosh team to keep the pain points visible to direct future changes to bosh abstractions (which seem now increasingly unlikely to ever happen).

**Describe the solution you'd like**

There is an unmerged implementation of a simple copy operation already (but with merge conflicts against latest master): cppforlife/go-patch#16

This functionality could be enough for our internal needs, so we would just create a fork of the project and update the PR to apply to the latest master. `move` is just `copy` followed by `remove`, so not really required, but should be trivial to add, if we want to keep the ops files even simpler.

**Additional context**

Compare the effort of moving log-cache "manually" in cloudfoundry-incubator/kubecf#619 compared to being able to have a simple ops file that moves the job within the cf-deployment manifest.

**Comment by jandubois** [comment]
We may want to use `qcopy` and `qmove` for the operation names, just for the unlikely event that upstream still implements `copy` and `move` with incompatible semantics.

**Comment by f0rmiga** [comment]
We forked https://github.com/SUSE/go-patch so it can be used to implement it.

**Comment by jandubois** [comment]
I've created https://github.com/SUSE/go-patch/pull/1 to implement qcopy/qmove ops.
